development:
  adapter: postgresql
  database: linkbox-development
  pool: 5
  timeout: 5000
  encoding: unicode
  username: linkbox
  password: 123123
  host: localhost

test:
  adapter: postgresql
  database: linkbox-test
  pool: 5
  timeout: 5000
  encoding: unicode
  username: linkbox
  password: 123123
  host: localhost

production:
  adapter: postgresql
  database: linkbox-production
  pool: 5
  timeout: 5000
  encoding: unicode
  username: linkbox
  password: 123123
  host: localhost
